on: [push]

jobs:
  jenkins-lts:
    runs-on: ubuntu-latest
    name: test on jenkins-lts
    steps:
      - uses: actions/checkout@v2
      - name: test jenkins-lts
        uses: ./.github/jenkins-lts/
